// src/layouts/shortcodes/Tabs.tsx
import { useState } from "react";
import React from "react";

const Tabs = ({
  tabs,
}: {
  tabs: { label: string; content: React.ReactNode }[];
}) => {
  const [activeTab, setActiveTab] = useState(0);

  return (
    <div className="">
      {/* Tab-Leiste */}
      <div className="flex gap-2">
        {tabs.map((tab, index) => (
          <button
            key={index}
            className={`flex-1 py-2 px-4 text-center border border-gray-200 rounded-lg  ${
              activeTab === index
                ? "border-gray-500 font-bold"
                : "text-gray-400"
            }`}
            onClick={() => setActiveTab(index)}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* Tab-Content */}
      <div className="mt-2">{tabs[activeTab].content}</div>
    </div>
  );
};

export default Tabs;

// src/layouts/components/ui/tabs.tsx
import {
  children,
  createSignal,
  For,
  type Component,
  type JSXElement,
} from "solid-js";

interface TabsProps {
  children: JSXElement;
}

export const Tabs: Component<TabsProps> = (props) => {
  const [activeTab, setActiveTab] = createSignal<number>(0);

  const tabs = children(() => props.children);
  const evaluatedTabs = () => tabs.toArray() as unknown as TabProps[];

  return (
    <div class="mx-auto w-full max-w-3xl">
      {/* Tab-Leiste */}
      <div class="mb-4 flex border-b">
        <For each={evaluatedTabs()}>
          {({ title }, index) => (
            <div class="flex-1 text-center">
              <button
                class="w-full border-b-2 px-4 py-2 transition-colors"
                classList={{
                  "font-bold border-gray-800": activeTab() === index(),
                  "border-transparent text-gray-600 hover:text-gray-800":
                    activeTab() !== index(),
                }}
                onClick={() => setActiveTab(index())}
              >
                {title}
              </button>
            </div>
          )}
        </For>
      </div>

      {/* Tab-Inhalt */}
      {evaluatedTabs()[activeTab()].children}
    </div>
  );
};

interface TabProps {
  title: string;
  children: JSXElement;
}
export const Tab: Component<TabProps> = (props) => {
  return props as unknown as JSXElement;
};
